### ISSUE TITLE
Support for nest v7

### ISSUE THREAD

**Issue by kirtan403** [agent-ly/nestjs-agenda#1]
I've been using this in production since a month. But when I tried this in one of my old project, it didn't work because of the peer dependency of nest ^8.2. Can we support nest v7 also?

**Comment by devlzcode** [comment]
Of course! I just need to make sure there are no issues.. for now I'll change the peer dependencies to align with https://github.com/nestjs/bull/blob/master/package.json since they follow the same design

**Comment by kirtan403** [comment]
Thank you so much!
