### ISSUE TITLE
How does the app.processor.ts work?

### ISSUE THREAD

**Issue by bloodred17** [agent-ly/nestjs-agenda#3]
The agendaService methods are working and creating entries in the database. But I don't understand how is the app.processor.ts in the example supposed to work?

**Comment by devlzcode** [comment]
If you are familiar with agenda, then doing `agenda.define(...)` will define a job while doing `agenda.schedule(...)` will schedule a job.

These two are the same:
```ts
agenda.define('sayHelloWorld', () => console.log('Hello world!'))
agenda.schedule('sayHelloWorld', 'in 1 minute')
// or if you want a repeating job, agenda.every('sayHelloWorld', '1 minute')
```

```ts
@Processor()
export class AppProcessor {
  @Define('sayHelloWorld')
  @Schedule('in 1 minute')
  // or if you want a repeating job, @Every('1 minute')
  sayHelloWorld() {
    console.log("Hello world!");
  }
}
```

**Comment by ubinatus** [comment]
@bloodred17 on #4 you can find an example of how to use the `app.processor.ts`
